# Generated by Django 2.2.1 on 2019-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=11, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=11, max_digits=19),
            preserve_default=False,
        ),
    ]
