# Generated by Django 2.2.1 on 2019-05-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='countrycode',
        ),
    ]
