# Generated by Django 2.2.1 on 2019-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190508_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
