# Generated by Django 2.2.1 on 2019-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
