# Generated by Django 2.2.1 on 2019-05-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20190506_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=255)),
                ('working', models.CharField(max_length=10, null=True)),
                ('date_of_leaving', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customusers',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='customusers',
            old_name='countrycode',
            new_name='country_code',
        ),
        migrations.AddField(
            model_name='customusers',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.Driver', unique=True),
            preserve_default=False,
        ),
    ]
