# Generated by Django 2.2.1 on 2019-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20190508_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
