# Generated by Django 2.2.1 on 2019-05-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20190506_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Driver'),
        ),
    ]
