# Generated by Django 2.2.1 on 2019-05-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20190506_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='employee_id',
        ),
    ]
