# Generated by Django 2.2.1 on 2019-05-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_remove_customusers_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.OneToOneField(default=26, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusers',
            name='type',
            field=models.CharField(choices=[('DR', 'DRIVER'), ('GS', 'GROUND_STAFF')], max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='working',
            field=models.BooleanField(max_length=10, null=True),
        ),
    ]
