# Generated by Django 2.2.1 on 2019-05-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20190506_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Upi_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='type',
            field=models.CharField(choices=[('DR', 'DRIVER'), ('C', 'CUSTOMER')], max_length=2),
        ),
    ]
