# Generated by Django 2.2.1 on 2019-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20190506_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
